### ISSUE TITLE
Mechanism to disregard specific ESMF hashes

### ISSUE THREAD

**Issue by theurich** [esmf-org/esmf-test-summary#2]
The list of test combos in the summary tables are generated as the union of combos found across all of the ESMF hashes recorded in the artifacts. Some config information (OS and NetCDF?) is actually harvested from the reports themselves. As a consequence, a "bad" ESMF hash - either because problematic code included, or just didn't work under some machines - can add a number of "spurious" combo rows (with OS and NetCDF as NONE).

After fixing the underlying issue, there is little value in keeping these rows, and really the ESMF-hash column that causes them in the first place. It would be nice to have a feature that allows filtering out specific ESMF hashes to not consider them in the summarization process. If the syntax is general enough, the same feature could probably also be used to cut off the columns at a specific "old" hash.

The list of filtered hashes should be easily configured and user accessible.

**Comment by rsdunlapiv** [comment]
It might be difficult/cumbersome to maintain a list of hashes to ignore - in this case I think you mean _artifacts_ hash - not ESMF hash, since it is a specific commit to the artifacts that is problematic.  E.g., these "gaea" rows have "None" in the NetCDF column because even the "make info" failed, so there is no way to glean the version of NetCDF that ESMF found/used.

59 | gaea | None | gfortran | 8.3.0 | mpi | 7.7.11 | g | None |   |   | 0 |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
60 | gaea | None | gfortran | 8.3.0 | mpi | 7.7.11 | O | None |   |   | 0 |   |  
61 | gaea | None | gfortran | 8.3.0 | mpiuni | None | O | None |   |   | 0 |   |  
62 | gaea | None | gfortran | 8.3.0 | mpiuni | None | g | None

Here's an example of one of these bad commits: 
https://github.com/esmf-org/esmf-test-artifacts/blob/b5c6fdeb446b5e9285a84ac44325a3886d899804/develop/gfortran/8.3.0/g/mpi/7.7.11/summary.dat

One option we have is while each artifact commit is being analyzed, if the summary.log is present but there is no "make info" information, then we consider it a "critical" failure for which we cannot determine the right combo.  We could simply skip over these, although that is not too satisfying as we'd like to know that the machine had a problem.

Maybe we could have a separate table with these kinds of failures so as not to clutter the main branch tables? It would be a kind of critical artifacts commits that need attention?  The downside of this is we have to remember to check it, since those values would not show up under the "develop" branch where we are usually looking.

**Comment by theurich** [comment]
@rsdunlapiv  I **was** actually referring to **ESMF hashes** here! The granularity with artifacts hashes seems definitely too fine and practically unmanagable.

So what I was thinking is that right now e.g. we could exclude ESMF hash  v8.4.0b07-5-g2f295f7. I am thinking that the decision to exclude such a hash is made a after there being at least one or two follow on columns... so like right now. We then see that excluding the ESMF hash does not remove any critical information. But it cleans up the table for better usage.

Further I thought that excluding specific hashes could maybe be implemented in a general way (like ranges, etc.) where it was possible to use it also to truncate the table as necessary. Killing two birds with one stone.

**Comment by rsdunlapiv** [comment]
This should be easy enough to implement at the database level, but we need to be thoughtful on how we would manage a list of ESMF hashes to ignore, since such a list could be cumbersome.

First, if there is some general principle that could be applied, that seems preferable to specifying individual hashes. We will eventually have to limit the number of columns anyway, perhaps by limiting the total days of history to show. If we show only the past 10 days of artifacts, for example, then eventually the bad hashes will naturally "fall off" the table (as will the spurious combo rows).

There may also be value in keeping "anchor" hashes, such as critical ESMF snapshots, so that we can see a coarser grained view of this history.  This approach would be something like:
- the first N columns are the most recent N ESMF hashes
- the second M columns contain only explicit tags (v8.4.0b06, v8.4.0b05, b8.4.0b04, etc.) without the intermediate hashes
- N and M would be configurable

If we decide that explicit, per-hash control is needed, I think a summarizer.yaml file could be introduced at the top-level of the esmf-test-summaries to configure the summarizer.  For example:

```yaml
# summarizer configuration

limit_days:  10  # stop processing after 10 days of history of the esmf-test-artifacts

filter:
  esmf_hash:
    - tagX-1-Z
    - tagX-2-V
    - [tagX - tagY]  # range of tags to exclude
 esmf_branch:
   - feature/already_merged   # exclude this branch
```

**Comment by theurich** [comment]
I like the summarizer.yaml file approach. I think it's the right way also to control the number of columns `M` and `N` in your description.

**Comment by rsdunlapiv** [comment]
@theurich I made a first pass at a summarizer.yaml configuration file that allows filtering the ESMF hashes and branches:

https://github.com/esmf-org/esmf-test-summary/blob/main/summarizer.yaml

The syntax supports a * as a wildcard when specifying hashes and branch names.  After modifying the summarizer.yaml in the repository above, you can manually kick off the job [here](https://github.com/esmf-org/esmf-test-summary/actions/workflows/generate-esmf-summaries.yml) to rebuild the summary tables.

I have this currently set to exclude hashes that match v8.4.0b07-* resulting in [this trimmed down summary table](http://earthsystemmodeling.org/esmf-test-summary/develop/index.html).

**Comment by theurich** [comment]
Very nice! Looking forward to using this when needed. The trimmed down version of the table looks great!

**Comment by theurich** [comment]
I think this is working and issue can be closed.
