### ISSUE TITLE
Permanent links for combos

### ISSUE THREAD

**Issue by theurich** [esmf-org/esmf-test-summary#6]
I am looking at the [table of all combinations](http://earthsystemmodeling.org/esmf-test-summary/index.html). The combos appear to be numbered according to the alphabetical order of machine name at the highest order. However, after that it is not clear to me what decides the ordering. I think the order of priority should be compiler, version, mpi, version, BOPT. Basically the same as is the order of columns (skipping OS of course).
There are regions of the table where it looks like the above is the order, but then there are other regions where it looks much more random within a specific machine.
I think having a strict order imposed on the combo numbering makes it easier to work with the table.

**Comment by rsdunlapiv** [comment]
Currently the combo numbering is determined by two things:
 (1) alphabetically by the machine name - this is because when going through the git history, the branches are sorted alphabetically and the summarizer goes through one branch at a time (e.g., starting with "acorn", etc.)
(2) after that, new combos are added as they appear in the artifacts commit history. So whichever combo happened to finish testing and push first for that machine will get the earliest combo number.

All that to say, it is somewhat random right now.  The combo id is mostly meaningless - just a convenient way to link to and reference a combo, not unlike a hash.  It is the primary key in the database for the combos and each test result record references a single combo id.

One option we have is after all the combos are ingested, we could sort them when they are retrieved from the DB and introduce a separate number that is orthogonal to the order in which the combos were ingested.  However, that might assign more meaning to the combo number than is really necessary -- it's just an identified to have a handle on a particular combo.

One other thing to keep in mind - you can sort my multiple columns by holding down shift and clicking additional columns in the table. So you can accomplish the sorting you referenced above in the existing table. There is probably a way to make the multi column sort the default when you first load the page to avoid the extra clicking each time.

**Comment by theurich** [comment]
Ah, I did not know about the multi-column sorting via shift. That does work nicely. Much nicer look through the table this way. Thanks!

I do still see benefit in eventually having relatively static combo numbering. E.g. I had just earlier written down that I needed to look at combo number 10, but a few minutes later I looked, combo 10 was a different one. This happened because a new report came in and so within the cheyenne subsection of the table things were reshuffled.

**Comment by rsdunlapiv** [comment]
Yes, that is a downside of the current approach.  It also means if you sent out a link to combos/10.html, the next time the summarizer runs that link may point to a different combo.  The current rationale was to keep the URLs short and simple, but we could introduce something more permanent like:

`combos/acorn_gfortran_8.10_openmpi_4.2_netcdf_4.7_g.html`

It's longer and uglier, but at least would not change over time.

**Comment by theurich** [comment]
Yes, I agree with long and ugly, but also that it is the most stable over time. Just also need to include _OS_ into the name, because it sometimes can lead to the rows with "None", which need to be distinguished.

**Comment by rsdunlapiv** [comment]
The permanent combo URLs have now been implemented.  A default sort has also been added to the combos table and branch summary table.

**Comment by theurich** [comment]
This looks great!
